SERVERMAIN_MKDIR := $(dir $(lastword $(MAKEFILE_LIST)))

SERVERMAIN_FLAGS := $(LIBOBJECTS_FLAGS) $(LIBUTILS_FLAGS) $(LIBSERVERCMD_FLAGS)\
                    $(SHARECMD_FLAGS) $(SHAREWRAP_FLAGS)

SERVERMAIN_SRCS := $(shell find $(SERVERMAIN_MKDIR) -type f -name '*.cpp')
SERVERMAIN_OBJS := $(patsubst %.cpp, $(BUILD_DIR)/%.o, $(SERVERMAIN_SRCS))\
				   $(LIBOBJECTS_OBJS) $(LIBUTILS_OBJS) $(SHAREWRAP_OBJS)
SERVERMAIN_LIBS := $(LIBOBJECTS_LIBS) $(LIBUTILS_LIBS) $(SHAREWRAP_LIBS)

ALL_DEPS += $(SERVERMAIN_OBJS:.o=.d)

SERVERMAIN_TARGET := $(BIN_DIR)/qg_server