SERVERMAIN_MKDIR := $(dir $(lastword $(MAKEFILE_LIST)))

SERVERMAIN_FLAGS := $(LIBOBJECTS_FLAGS) $(LIBUTILS_FLAGS) $(LIBSERVERCMD_FLAGS)

SERVERMAIN_SRCS := $(shell find $(SERVERMAIN_MKDIR) -type f -name '*.cpp')
SERVERMAIN_OBJS := $(patsubst %.cpp, $(BUILD_DIR)/%.o, $(SERVERMAIN_SRCS))\
				   $(LIBOBJECTS_OBJS) $(LIBUTILS_OBJS)
SERVERMAIN_LIBS := $(LIBOBJECTS_LIBS) $(LIBUTILS_LIBS) $(LIBSERVERCMD_LIBS)
SERVERMAIN_DEPS := $(SERVERMAIN_OBJS:.o=.d)

SERVERMAIN_TARGET := $(BIN_DIR)/qg_server