DBWORKER_MKDIR := $(dir $(lastword $(MAKEFILE_LIST)))

DBWORKER_FLAGS := $(LIBMARIADB_FLAGS) $(LIBOBJECTS_FLAGS)\
                  $(LIBUTILS_FLAGS) $(LIBSERVERCMD_FLAGS)

DBWORKER_SRCS := $(shell find $(DBWORKER_MKDIR) -type f -name '*.cpp')
DBWORKER_OBJS := $(patsubst %.cpp, $(BUILD_DIR)/%.o, $(DBWORKER_SRCS))\
                 $(LIBMARIADB_OBJS) $(LIBOBJECTS_OBJS) $(LIBUTILS_OBJS)
DBWORKER_LIBS := $(LIBMARIADB_LIBS) $(LIBOBJECTS_LIBS)\ 
                 $(LIBUTILS_LIBS) $(LIBSERVERCMD_LIBS)
DBWORKER_DEPS := $(DBWORKER_OBJS:.o=.d)


DBWORKER_TARGET := $(BIN_DIR)/db_worker