PLAYINGROOM_MKDIR := $(dir $(lastword $(MAKEFILE_LIST)))

PLAYINGROOM_FLAGS := $(LIBOBJECTS_FLAGS) $(LIBUTILS_FLAGS) $(LIBSERVERCMD_FLAGS)\
                	 $(SHARECMD_FLAGS) $(SHAREWRAP_FLAGS) $(SHAREBOARD_FLAGS)

PLAYINGROOM_SRCS := $(shell find $(PLAYINGROOM_MKDIR) -type f -name '*.cpp')
PLAYINGROOM_OBJS := $(patsubst %.cpp, $(BUILD_DIR)/%.o, $(PLAYINGROOM_SRCS))\
            		$(LIBOBJECTS_OBJS) $(LIBUTILS_OBJS) $(SHAREWARP_OBJS) $(SHAREBOARD_OBJS)
PLAYINGROOM_LIBS := $(LIBOBJECTS_LIBS) $(LIBUTILS_LIBS) $(SHAREWRAP_LIBS) $(SHAREBOARD_LIBS)

ALL_DEPS += $(PLAYINGROOM_OBJS:.o=.d)

PLAYINGROOM_TARGET := $(BIN_DIR)/playing_room