LIBUTILS_MKDIR := $(dir $(lastword $(MAKEFILE_LIST)))

LIBUTILS_FLAGS := -I$(LIBUTILS_MKDIR)include $(SHAREWRAP_FLAGS)

LIBUTILS_SRCS := $(wildcard $(LIBUTILS_MKDIR)src/*.cpp)
LIBUTILS_OBJS := $(patsubst %.cpp, $(BUILD_DIR)/%.o, $(LIBUTILS_SRCS)) $(SHAREWRAP_OBJS)
LIBUTILS_LIBS := $(SHAREBOARD_LIBS) $(SHAREWRAP_LIBS)

ALL_DEPS += $(LIBUTILS_OBJS:.o=.d)