LIBOBJECTS_MKDIR := $(dir $(lastword $(MAKEFILE_LIST)))

LIBOBJECTS_FLAGS := -I$(LIBOBJECTS_MKDIR)/include

LIBOBJECTS_SRCS := $(LIBOBJECTS_MKDIR)/src/*.cpp
LIBOBJECTS_OBJS := $(patsubst %.cpp, $(BUILD_DIR)/%.o, $(LIBOBJECTS_SRCS))
LIBOBJECTS_DEPS := $(LIBOBJECTS_OBJS:.o=.d)
LIBOBJECTS_LIBS := 