LIBOBJECTS_MKDIR := $(dir $(lastword $(MAKEFILE_LIST)))

LIBOBJECTS_FLAGS := -I$(LIBOBJECTS_MKDIR)include\
					  $(SHAREBOARD_FLAGS) $(SHAREWRAP_FLAGS)

LIBOBJECTS_SRCS := $(wildcard $(LIBOBJECTS_MKDIR)src/*.cpp)
LIBOBJECTS_OBJS := $(patsubst %.cpp, $(BUILD_DIR)/%.o, $(LIBOBJECTS_SRCS))\
				   $(SHAREBOARD_OBJS) $(SHAREWRAP_OBJS)
LIBOBJECTS_LIBS := $(SHAREBOARD_LIBS) $(SHAREWRAP_LIBS)

ALL_DEPS += $(LIBOBJECTS_OBJS:.o=.d)